FROM debian:bookworm-slim

WORKDIR /workspace

RUN apt update && apt install -y \
    curl \
    git \
    bash \
    build-essential \
    pkg-config \
    libssl-dev \
    libdbus-1-dev \
    libudev-dev \
 && rm -rf /var/lib/apt/lists/*

# Instalar Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup target add wasm32-unknown-unknown wasm32v1-none

# Nightly toolchain (requerido por cargo-scout-audit)
RUN rustup toolchain install nightly \
 && rustup component add clippy --toolchain nightly

RUN cargo install --locked soroban-cli
RUN cargo install cargo-scout-audit

CMD ["tail", "-f", "/dev/null"]
